name: Makefile CI *

on:
  push:
    branches: [ "main", "prod", "release" ]
  pull_request:
    branches: [ "main", "prod", "release" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: configure
      run: ./configure

    - name: github
      run: ./github

    - name: *
      run: ./*

    - name: Install dependencies
      run: make *

    - name: Run check
      run: make * check

    - name: Run distcheck
      run: make * distcheck
